### ISSUE TITLE
multi-level JSON highlighting: How did you do it?

### ISSUE THREAD

**Issue by bcomnes** [josh-kaplan/sublime-monokai-neue#2]
Love the theme!  I wanted to add a similar feature to my favorite color scheme but it looks rather tedious.

I was wondering how you were able to get multi-level JSON highlighting working?  Did you hand edit a bunch of scope levels worth of unique colors?  Do you have a way to generate some pattern of varying colors? Is there a way to dynamically color based on scope depth? Any info helps 💯

**Comment by josh-kaplan** [comment]
I based the theme's JSON highlighting on MonokaiJSON Plus. They had a [Python script](https://github.com/ColibriApps/MonokaiJsonPlus/blob/development/code/generateRules.py) to generate all of that. I took that and modified it a bit for my needs. I can upload that too if you want my dev tool as well.

**Comment by bcomnes** [comment]
Yeah that would be great!

**Comment by josh-kaplan** [comment]
I created a branch called dev and checked my dev tools into there.

**Comment by bcomnes** [comment]
Thanks @josh-kaplan !
