### ISSUE TITLE
Python strings look like comments on build 3114

### ISSUE THREAD

**Issue by jerivas** [josh-kaplan/sublime-monokai-neue#3]
Hey there! Please let me know if this is the wrong place to post this.

I've been using Monokai Neue for a while (and loving it!), but I noticed that after Sublime upgraded to build 3114, Python strings are highlighted like comments. They used to be yellow and now they're grey. They are also always italiced.
### Default Monokai

![screenshot from 2016-05-17 15-38-46](https://cloud.githubusercontent.com/assets/2391102/15340269/cf06d786-1c45-11e6-8227-6cc518c9531d.png)
### Monokai Neue

![screenshot from 2016-05-17 15-37-49](https://cloud.githubusercontent.com/assets/2391102/15340283/e0bb9a0c-1c45-11e6-9675-e98e334f2a1b.png)

It's hard to tell strings apart from comments this way.

**Comment by josh-kaplan** [comment]
I've been using [PythonImproved](https://github.com/MattDMo/PythonImproved) as for my Python development, so I didn't notice the problem. I'll see if I can find out what I can do to fix it for the default Python syntax. 

But I do recommend trying PythonImproved, it has a few good changes over the default Python highlighting.

**Comment by josh-kaplan** [comment]
Added a fix and created a patch release [1.1.1](https://github.com/josh-kaplan/sublime-monokai-neue/releases/tag/1.1.1). The issues stems from me trying to highlight Python docstrings as comments. This fixes the issue for Python, but now PythonImproved highlights docstrings as regular strings.

**Comment by jerivas** [comment]
Thanks for the quick fix! It's working great now.
